spring:
  thymeleaf:
    cache: false
  jpa:
    generate-ddl: true
    show-sql: false

server:
  session:
    timeout: 7200
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

levelap:
  securityEnabled: true
  allowedOrigins: http://localhost,
                  http://local.gameclub,
                  http://local.admin.gameclub,
                  http://local.beta.gameclub,
                  http://gameclub.levelaptesting.com,
                  http://admin.gameclub.levelaptesting.com,
                  http://beta.gameclub.levelaptesting.com,
                  http://www.gameclub.levelaptesting.com,
                  http://www.admin.gameclub.levelaptesting.com,
                  http://www.beta.gameclub.levelaptesting.com,
                  http://104.197.235.122,
                  https://admin.gameclub.com.ec,
                  https://beta.gameclub.com.ec,
                  https://www.gameclub.com.ec,
                  https://104.198.238.150
  compressRequest: true
  file:
    environment: GAMECLUB_HOME
  blog:
    comment-page-size: 3
    home-page-size: 4
    important-size: 3
    most-seen-size: 4
    search-size: 10

flyway:
  enabled: true
  schemas:
    - gameclub
    - commons
  locations:
    - classpath:db/gameclub
    - classpath:db/commons
  baseline-on-migrate: true
  encoding: UTF-8
  out-of-order: true
  
kushki-configuration:
  show-log: true
  private-merchant-id: 10000002423281133314149322144567
  end-point:
    path: https://api-uat.kushkipagos.com/v1
    
priceCharting-configuration:
  url: http://www.pricecharting.com/api/product
  
tcc-configuration:
  key: ECTOMORROW
  url: http://clientes.tcc.com.co/preservicios
  account: 6019000
  nit: 1792738865001